### ISSUE TITLE
IntegrityError

### ISSUE THREAD

**Issue by HNKNTA** [jlecker/django-responsive-images#2]
Just install this and constantly get error when open my page:
`(1062, "Duplicate entry '6-118-30-nocrop' for key 'responsive_images_resizedimage_original_id_88516b12_uniq'")`
My django version is 1.9.1. Is it too new for responsive-images?

**Comment by jlecker** [comment]
Fixed in version 1.0.3. I have tested with Django 1.9 and I know of no problems.
