### ISSUE TITLE
Table 'myproj.responsive_images_originalimage' doesn't exist

### ISSUE THREAD

**Issue by ursomniac** [jlecker/django-responsive-images#4]
I'm trying to use your DRI in an existing project (i.e, I already have models, etc built with content in them for a site already in production).  I tried migrating but nothing was picked up.

Are there any additional steps that have to be taken to set this up other than what's in the documentation?

If there's supposed to be a responsive_image_originalimage table, how do we get it there?

**Comment by jlecker** [comment]
I originally made this before Django had migrations built-in, so it doesn't come with any. I'll add them and release a new version when I have time, but for a workaround you should be able to just make the migrations yourself. Try running `python manage.py makemigrations responsive_images` to create a migration (and then migrate again).

**Comment by jlecker** [comment]
@ursomniac Did this work for you?

**Comment by selmanceker** [comment]
I am also having same problem. I have created a migration using `python manage.py makemigrations responsive_images` then tried to migrate it but nothing is migrated. @jlecker

**Comment by cpcbell** [comment]
Running make migrations with the package name "responsive_images" worked for me.  Thx man!

**Comment by svenkaemper** [comment]
> 

Any chance the needed migrations will be included in a new release? And thanks for the work so far, it's a very useful app!

**Comment by jlecker** [comment]
I didn't realize anyone was still using this, to be honest! I'll see if I can put together an update.
